### ISSUE TITLE
Support Elastic search query syntax subset on paginated endpoints

### ISSUE THREAD

**Issue by pboers1988** [workfloworchestrator/orchestrator-core#288]
Make sure we start supporting the Elastic query syntax on the subscriptions and processes endpoint.

Apply to all endpoints, e.g. subscriptions, products.

Required features of the Elastic Query syntax:
- Field/value filter, single words do not need quotes `insync:true` `description:SURF`
- Field/value filter, multiple words require double quotes: `description:"SURFdomain test"`
- For subscriptions endpoint only -- Value filter, single word without fieldname: `SURF` assumes using the "tsv" field. The given example is the equivalent to `tsv:SURF`

Endpoint should respond with an error when the query is invalid.

**Comment by srichmond** [comment]
Part of this is to ensure that we retain the current filtering, but extend the potential queries to include "or" and "not" filtering options.

**Comment by ricardovdheijden** [comment]
Frontend currently uses the EuiSearchBar:
https://elastic.github.io/eui/#/forms/search-bar

**Comment by dmarjenburgh** [comment]
Some points to clarify and disambiguate this issue.

- We do not require full elastic search query syntax, but a subset of the functionality described here: https://elastic.github.io/eui/#/forms/search-bar. For the moment:
  - Phrasing (quotes around consecutive words:` "SURFdomain test"`
  - Disjunction (The keyword `OR` (outside of quotes) is a supported operator finding the union of subqueries)
  - Negation (The hyphen/minus-sign `-` in front of a term to omit results matching the negated term)
  - Field/value search (Semicolon `:` for `key:value` matches. Key or value could be quoted)
 
To keep the implementation simple, we should rely as much as possible on the fulltext search capabilities of PostgreSQL and avoid building our own parsing logic. We currently use the `websearch_to_tsquery` function that performs almost all of the above requirements. https://www.postgresql.org/docs/15/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES

The current implementation is rather complex and we can use the new GraphQL endpoint to simplify the API considerably.
Complexity of the current `/api/subscriptions` REST endpoint:
- The `filters` query parameter has an awkward interface that is badly documented and hard to understand. It accepts a comma separated list of items that is treated like a list of key-value pairs (`?filters=filter1,value1,filter2,value2`) It is not clear which filter values are supported.
- There is support for inequality filters by changing the field name (`"numeric_field_gt,20" => WHERE subscription.numeric_field > 20`). But this functionality is half-broken and doesn't work for all field types.
- There is some unnecessary special handling of filters like tag, tags, product, status, statuses etc. Some are legacy.
- The `tsv` filter is a user-specified full-text search string. I have a lot of gripes with this thing:
  - `tsv` stands for `tsvector` or `text search vector` which is a Postgres type. The name is confusing and should not be part of the API. I propose to just use `q` or `query` in the GraphQL API. (@srichmond mentioned `elastic_query`. As we don't really adhere to the full elastic search syntax. Maybe we should just name it `q(uery)`)
  - Since the value is user-defined, it can contain comma's which messes up the handling of the `filters` query parameter, which is split by `,` and partitioned into pairs.
  - The `tsv` value is supplied to Postgres's `websearch_to_tsquery` and also supports `key:value` searches (by (ab)using quoting). This creates ambiguity in where to specify filters. You can add `status:inactive` in the tsv value which works just the same.

## Proposal

The GraphQL endpoint for subscriptions will have the following arguments schema:
- `first: Int!` (Already there)
- `after: Int!` (Already there)
- `sortBy: [SubscriptionsSort!]` (Already there)
- `query: String` (Replacement for `filterBy` and `tsv`)

Clients will only have to specify pagination (`first`/`after`) options, sorting (`sortBy`) options and a single text query `query`. The backend can decide to use the full-text capabilities or parse out specific field filters like `insync` and `status` for better performance (these fields can be filtered on the `subscription` table instead of the `subscriptions_search` view). This keeps the API simple to use.

## Future improvements
We can extend the supported query syntax with inequalities like `port_speed>9000` in the future. This might require custom parsing on our end.

**Comment by pboers1988** [comment]
This is the internal SURF issue for this implementation. We will  pick it up from here!

### Summary

Provide a specification of the supported query string syntax for full-text search endpoint

### Description

The supported syntax will be a subset of the `simple query string` syntax of ElasticSearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

The following constraints must be met:

- Accept only a single string as input (no flags as in an ES query)
  * No specific field flags. All fields will be searched.
- Usable for search boxes. Tolerant. No errors for invalid syntax.
- Supported operators:
  * `+` signifies `AND` operation. This is the default
  * `|` signifies `OR` operation
  * `-` negates a token
  * `"` wraps a number of tokens to signify a phrase
  * `*` at the end of a term signifies a prefix query
  * `(` and `)` allow grouping. Signifies precedence.

The following limitations are acceptable and maybe necessary. Either for performance or simplicity:

- No regex or arbitrary wildcard support. We CAN support prefix matching!
  * `name:jo?n` - NO
  * `name:jo*` - MAYBE YES
- Term or field boosting
- Fuzzy or proximity searching
- Arbitrary ranges
  * `count:[1 TO 10]` - NO
  * `created_at:<=2023-01-01` - Maybe, but only for specific fields
- No specific field flags. All fields will be searched.
- Unsupported operators:
  * `~N` after a word signifies edit distance (fuzziness)
  * `~N` after a phrase signifies slop amount

# Search query grammar

```plaintext
<Query> ::= <OrExpression>
<OrExpression> ::= <AndExpression> (<OrOperator> <AndExpression>)*
<OrOperator> ::= ' or ' | ' | '
<AndExpression> ::= <Group> | <Terms>
<Group> ::= '(' <Terms> ')'
<Terms> ::= <Term>*
<Term> ::= <NegativeTerm> | <PositiveTerm>
<NegativeTerm> ::= '-' <PositiveTerm>
<PositiveTerm> ::= <Phrase> | <KVTerm> | <Token>
<Phrase> ::= '"' <Token>* '"'
<KVTerm> ::= <Value> ':' (<Value> | <ValueGroup>)
<Token> ::= <Word> | <PrefixWord>
<Word> ::= <text without [ "*()] and no starting '-'>
<PrefixWord> ::= <Word> '*'
<Value> ::= <Phrase> | <Token>
<ValueGroup> ::= '(' <Value> (<OrOperator> <Value>)* ')'
```

**Comment by tjeerddie** [comment]
search in subscriptions graphql resolver is moved to https://github.com/workfloworchestrator/orchestrator-core/issues/413

**Comment by pboers1988** [comment]
Implemetend in #412
