### ISSUE TITLE
Look into usage of server-sent events as an alternative to websockets

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#373]
We dont need to stream data from client to the server, so using websocket is kind of overkill and server-sent events could be a better replacement, which provides a one way stream from server to client.

https://github.com/sysid/sse-starlette

**Comment by crankynetman** [comment]
I'm not sure that we care too much about this, but SSE does apparently not work with Internet Explorer 😁. 

https://caniuse.com/?search=server-sent%20events

**Comment by crankynetman** [comment]
And a few notes I found across the web about antivirus implications of SSE:

https://medium.com/developer-rants/antivirus-software-blocking-javascript-server-side-events-fb505f768c6
https://stackoverflow.com/questions/63716882/server-side-events-blocked-by-antivirus


It seems to me that most of the issues in this domain might be due to people creating updates that don't conform to the w3c standards, so i'd reckon that if we just make sure that we follow their guidelines, it will be a non-issue for us.

**Comment by Sparrow1029** [comment]
Some more caveats regarding SSE:

- [This answer on SO](https://stackoverflow.com/a/72591015/6768111) details the issue that Firefox & Chrome for HTTP/1 only allow 6 SSE connections per domain
- HTTP/2 fixes this issue (see [Mozilla MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#sect1))
  - at least for ESnet, we are serving the FastAPI orchestrator-core application using `uvicorn`, which does _not_ support HTTP/2.
  - The `hypercorn` library (officially [documented](https://fastapi.tiangolo.com/deployment/manually/#install-the-server-program) in FastAPI) for serving you application) _does_ support HTTP/2, so this may not be a problem if downstream users can switch to that library.

**Comment by pboers1988** [comment]
@hanstrompert if it's a won't fix? I guess we'll be using websockets?

**Comment by hanstrompert** [comment]
I guess the 'wontfix' deserves some explanation 😊  In a discussion with @anieuwland and @wouter1975 we decided to postpone the implementation of WebSockets or SSE in the new frontend for now. Looking back, the main reason that we implemented WebSockets in the current fronted is because the polling triggered a spinner that was visible to the user. We trust that in the new frontend this visual artefact can be avoided by better separation of the polling from the other regular data fetching. This way we can avoid introducing functionality we do not actually need, thus saving resources now and on future maintenance.

**Comment by pboers1988** [comment]
A larger impetus for implementing websockets was also performance. I would like to see that we attempt to re-use the existing tools to have Websockets. Furthermore a correct implementation will also increase the usability of the FE will discuss with @wouter1975

**Comment by pboers1988** [comment]
Will be using websockets
